name: yubidart
description: Yubico Services for Dart and Flutter. OTP Validation with Yubikey
homepage: https://github.com/reddwarf03/yubidart

version: 1.0.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  crypto: ^3.0.1

  # A composable, multi-platform, Future-based API for HTTP requests
  http: ^0.13.4

  # Flutter plugin for accessing the NFC features on Android and iOS.
  nfc_manager: ^3.1.0

  # Nonce contains a static generator that generates random alphanumeric strings, and can be constructed as an object containing a generated string
  nonce: ^1.2.0

dev_dependencies:
  # Automatically organize your dart imports
  import_sorter: ^4.6.0
  test: ^1.19.5